name: Cohort
options:
  bundleIdPrefix: com.ayanmukherjee
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true
  defaultSourceDirectoryType: group
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  Cohort:
    type: application
    platform: iOS
    sources:
      - path: Cohort/App
      - path: Cohort/Core
      - path: Cohort/DesignSystem
      - path: Cohort/Features
      - path: Cohort/Models
      - path: Cohort/Services
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ayanmukherjee.cohort
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies: []
